# Generated by Django 6.0.5 on 2026-05-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('notice', 'Comunicado'), ('internship', 'Estágio'), ('job', 'Vaga de emprego'), ('event', 'Evento'), ('academic', 'Acadêmico')], default='academic', max_length=20),
        ),
    ]
