# Generated by Django 6.0.5 on 2026-05-24 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_event_date_academiccalendar_start_date_and_more'),
        ('management_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicfile',
            name='file_type',
            field=models.CharField(choices=[('material', 'Material do professor'), ('submission', 'Entrega do aluno'), ('document', 'Documento acadêmico')], default='submission', max_length=20),
        ),
        migrations.AddField(
            model_name='academicfile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='contact_type',
            field=models.CharField(choices=[('academic', 'Acadêmico'), ('financial', 'Financeiro'), ('technical', 'Suporte técnico'), ('secretary', 'Secretaria'), ('other', 'Outro')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='destination',
            field=models.CharField(default='Secretaria Acadêmica', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='return_channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('portal', 'Portal')], default='email', max_length=20),
        ),
        migrations.CreateModel(
            name='FinancialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendente'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito')], default='pix', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
