# Generated by Django 6.0.5 on 2026-05-24 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_teacherprofile_classgroup_classenrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccalendar',
            old_name='event_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='event_type',
            field=models.CharField(choices=[('class', 'Aula'), ('holiday', 'Feriado'), ('exam', 'Prova'), ('final_exam', 'Prova Final'), ('enrollment', 'Matrícula'), ('event', 'Evento'), ('notice', 'Comunicado')], default='event', max_length=20),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='visible_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprovado'), ('attention', 'Em atenção'), ('failed', 'Reprovado'), ('pending', 'Sem nota')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='period',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('current', 'Em andamento'), ('completed', 'Concluída'), ('failed', 'Reprovada'), ('locked', 'Bloqueada')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.teacherprofile')),
            ],
        ),
    ]
