# Generated by Django 6.0.5 on 2026-10-10 00:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_normalize_subject_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.classgroup'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='academic.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='academic.studentprofile'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academic.classgroup'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academic.studentprofile'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.classgroup'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.studentprofile'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.subject'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academic.classgroup'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.studentprofile'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.subject'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_schedules', to='academic.classgroup'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.subject'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.teacherprofile'),
        ),
        migrations.AddConstraint(
            model_name='academiccalendar',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='calendar_date_order'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='term_date_order'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='assessment_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_score__gt', 0)), name='assessment_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='assessment_score_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), models.Q(('grade__gte', 0), ('grade__lte', 10)), _connector='OR'), name='grade_score_range'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1), ('attempt__lte', 2)), name='grade_attempt_range'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(condition=models.Q(('class_group__isnull', True)), fields=('student', 'subject', 'attempt'), name='uniq_legacy_grade_attempt'),
        ),
        migrations.AddConstraint(
            model_name='weeklyschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_time_order'),
        ),
    ]
